[book]
authors = ["zejun"]
language = "zh-hans"  # 改为中文，这样搜索插件会更好地支持中文
title = "嵌入式面试题精选" # 你的书名

[output.html]
# 这里的配置有助于 GitHub Pages 正确处理路径
# 并且会开启漂亮的主题和搜索功能
default-theme = "light"
preferred-dark-theme = "navy"
copy-fonts = true

[output.html.search]
limit-results = 30
use-boolean-and = true
boost-title = 2